version: "3.8"
volumes:
  db-store:
services:
  web:
    build: 
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./backend:/work/backend
      - ./infra/docker/php/bash/.bash_history:/root/.bash_history

  db:
    build: 
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
